### ISSUE TITLE
How to train predictive trajectory model?

### ISSUE THREAD

**Issue by Alex-fishred** [TomatoFT/Vehicle-Trajectory-Prediction-Veh2Veh#2]

**Comment by TomatoFT** [comment]
You can find the data (after the automation stage) here: https://www.kaggle.com/datasets/tonchow/uit-vehpredtraj-dataset.
You can see the colab notebook for training the models here: https://colab.research.google.com/drive/1cmuh40m8CoNlMCn6_GFf8nw4bNr-Tz9O?usp=sharing
